name: doctor_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  jpush_flutter: 2.1.4
  cupertino_icons: ^1.0.2
  fl_chart: ^0.45.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  share: ^2.0.4
  flutter_slidable: ^1.2.0
  dio: 4.0.4
  path_provider: 2.0.8
  webview_flutter: 3.0.0
  provider: 6.0.1
  permission_handler: ^8.2.0
  json_annotation: 4.4.0
  package_info: 2.0.2
  connectivity: 3.0.6
  device_info: 2.0.3
  url_launcher: 6.0.17
  android_intent: 2.0.2
  shared_preferences: 2.0.10
  flutter_localizations:
    sdk: flutter
  loading_indicator: ^2.0.1
  crypto: ^3.0.1
  image_picker: ^0.8.4
  video_thumbnail: ^0.4.3
  record: ^2.1.1
  geolocator: ^7.0.3
  # tpns_flutter_plugin:
  #   path: /Users/xingchenhe/Documents/work/TPNS-Flutter-Plugin
  localstorage: ^4.0.0+1
  adaptive_dialog: ^0.10.0+5
  mime_type: ^1.0.0
  file_picker: ^4.2.1
  #  provider: ^5.0.0 #Flutter2用这个
  #  cached_network_image: 1.1.1 # 1.9版本flutter
  #  cached_network_image: 2.0.0 #1.22.5版本Flutter用这个
  cached_network_image: ^3.2.0
  #图片显示
  photo_view: ^0.13.0
  flutter_sound: ^9.1.3
  #权限处理
  #音频处理
  #  audioplayers: 0.13.3 #1.22.5版本Flutter用这个
  audioplayers: ^0.20.1
  #视频播放
  #  video_player: 0.10.11+2 #1.22.5版本Flutter用这个
  video_player: ^2.2.19
  #图片压缩
  flutter_image_compress: ^1.1.0
  #拼音
  lpinyin: ^2.0.3
  #特殊列表滑动
  azlistview: ^2.0.0
  #微信图库
  #  wechat_assets_picker: ^4.2.1 #1.22.5版本Flutter用这个
  #  wechat_assets_picker: ^5.4.0 #Flutter2用这个
  wechat_assets_picker: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/2.0x/userIcon@2x.png
    - images/2.0x/pasIcon@2x.png
    - images/2.0x/LoginbackGrond@2x.png
    - images/2.0x/check box@2x.png
    - images/2.0x/check box-select@2x.png
    - images/2.0x/back.png
    - images/2.0x/more@2x.png
    - images/2.0x/success@2x.png
    - images/2.0x/abnormal-not sel.png
    - images/2.0x/home page-not sel.png
    - images/2.0x/my-not sel.png
    - images/2.0x/abnormal-sel.png
    - images/2.0x/home page-sel.png
    - images/2.0x/my-sel.png
    - images/2.0x/hidePas@2x.png
    - images/2.0x/showPsa@2x.png
    - images/back.png
    - images/abnormal-not sel.png
    - images/home page-not sel.png
    - images/my-not sel.png
    - images/abnormal-sel.png
    - images/home page-sel.png
    - images/my-sel.png
    - images/background.png
    - images/pulldown.png
    - images/new.png
    - images/search.png
    - images/backgroundFrist.png
    - images/notice.png
    - images/hidePas.png
    - images/showPsa.png
    - assets/images/
    - assets/images/home/
    - assets/images/my/
    - assets/images/svg/
    - assets/images/bsc.webp
    - assets/images/bar_close.png
    - assets/images/tabbar_contacts_c.webp
    - assets/images/tabbar_contacts_s.webp
    - assets/images/tabbar_discover_c.webp
    - assets/images/tabbar_discover_s.webp
    - assets/images/tabbar_chat_c.webp
    - assets/images/tabbar_chat_s.webp
    - assets/images/tabbar_me_c.webp
    - assets/images/tabbar_me_s.webp
    - assets/images/def_avatar.png
    - assets/images/search_black.webp
    - assets/images/search_white.png
    - assets/images/Contact_Female.webp
    - assets/images/Contact_Male.webp
    - assets/images/right_more.png
    - assets/images/favorite.webp
    - assets/images/contacts_add_newmessage.png
    - assets/images/add_addressicon.png
    - assets/images/ic_delete.webp
    - assets/images/ic_right_arrow_black.webp
    - assets/images/ic_right_arrow_grey.webp
    - assets/images/ic_add_friend.webp
    - assets/images/ic_no_data.webp
    - assets/images/login/select_avatar.webp
    - assets/images/login/ic_select_have.webp
    - assets/images/login/ic_select_have_grey.webp
    - assets/images/login/ic_select_no.png
    - assets/images/chat/ic_Emotion.webp
    - assets/images/chat/ic_Keyboard.webp
    - assets/images/chat/ic_details_add.png
    - assets/images/chat/ic_voice.webp
    - assets/images/chat/ic_chat_more.webp
    - assets/images/chat/ic_chat_voice.webp
    - assets/images/chat/ic_details_camera.webp
    - assets/images/chat/ic_details_card.webp
    - assets/images/chat/ic_details_favorite.webp
    - assets/images/chat/ic_details_file.webp
    - assets/images/chat/ic_details_localtion.webp
    - assets/images/chat/ic_details_media.webp
    - assets/images/chat/ic_details_photo.webp
    - assets/images/chat/ic_details_red.webp
    - assets/images/chat/ic_details_transfer.webp
    - assets/images/chat/ic_details_video.webp
    - assets/images/chat/voice_volume_1.webp
    - assets/images/chat/voice_volume_2.webp
    - assets/images/chat/voice_volume_3.webp
    - assets/images/chat/voice_volume_4.webp
    - assets/images/chat/voice_volume_5.webp
    - assets/images/chat/voice_volume_6.webp
    - assets/images/chat/voice_volume_7.webp
    - assets/images/chat/sound_left_0.webp
    - assets/images/chat/sound_left_1.webp
    - assets/images/chat/sound_left_2.webp
    - assets/images/chat/sound_left_3.webp
    - assets/images/chat/sound_right_0.png
    - assets/images/chat/sound_right_1.webp
    - assets/images/chat/sound_right_2.webp
    - assets/images/chat/sound_right_3.png
    - assets/images/chat/icon_sight_close.png
    - assets/images/chat/flip_camera_icon_nor.webp
    - assets/images/mine/ic_small_code.png
    - assets/images/mine/ic_wallet.webp
    - assets/images/mine/ic_card_package.png
    - assets/images/mine/ic_emoji.png
    - assets/images/mine/ic_pay.png
    - assets/images/mine/ic_setting.png
    - assets/images/contact/ic_contacts_details.png
    - assets/images/contact/ic_no_public.webp
    - assets/images/contact/ic_tag.webp
    - assets/images/contact/ic_group.webp
    - assets/images/contact/ic_new_friend.webp
    - assets/images/contact/ic_video.png
    - assets/images/contact/ic_voice.png
    - assets/images/contact/ic_offical.webp
    - assets/images/contact/ic_reda.webp
    - assets/images/contact/ic_scanqr.webp
    - assets/images/contact/ic_search_wework.webp
    - assets/images/contact/ic_contact_add.webp
    - assets/images/discover/ff_Icon_album.webp
    - assets/images/discover/ff_Icon_shake.webp
    - assets/images/discover/ff_Icon_bottle.webp
    - assets/images/discover/ff_Icon_browse.webp
    - assets/images/discover/ff_Icon_nearby.webp
    - assets/images/discover/ff_Icon_qr_code.webp
    - assets/images/discover/ff_Icon_search.webp
    - assets/images/discover/game_center_h5.webp
    - assets/images/discover/mini_program.webp
    - assets/images/emoji/
    - assets/images/group/
    - assets/images/wechat/
    - assets/data/contacts.json
    - assets/data/friends.json


  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/PingFang-SC-Regular.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/PingFang-SC-Medium.ttf
    - family: ShouShuti
      fonts:
        - asset: assets/fonts/ShouShuti_Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
