name: doctor_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  jpush_flutter: 2.1.4
  #广播
  event_bus: ^2.0.0
  flutter_chat_ui: ^1.5.5
  zego_express_engine: ^2.17.1
  cupertino_icons: ^1.0.2
  fl_chart: ^0.45.1
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  share: ^2.0.4
  flutter_slidable: ^1.2.0
  dio: 4.0.4
  intl: ^0.17.0
  mime: ^1.0.1
  uuid: ^3.0.5
  diffutil_dart: ^3.0.0
  equatable: ^2.0.3
  flutter_chat_types: ^3.3.1
  flutter_link_previewer: ^2.6.3
  meta: ^1.7.0
  visibility_detector: ^0.2.2
  path_provider: 2.0.8
  webview_flutter: 3.0.0
  provider: 6.0.1
  permission_handler: ^8.2.0
  json_annotation: 4.4.0
  package_info: 2.0.2
  connectivity: 3.0.6
  device_info: 2.0.3
  url_launcher: ^6.0.18
  android_intent: 2.0.2
  shared_preferences: 2.0.10
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.4
  video_thumbnail: ^0.4.3
  record: ^2.1.1
  flutter_easyloading: ^3.0.3
  open_file: ^3.2.1
  # tpns_flutter_plugin:
  #   path: /Users/xingchenhe/Documents/work/TPNS-Flutter-Plugin
  localstorage: ^4.0.0+1
  adaptive_dialog: ^0.10.0+5
  file_picker: ^4.2.1
  #  provider: ^5.0.0 #Flutter2用这个
  #  cached_network_image: 1.1.1 # 1.9版本flutter
  #  cached_network_image: 2.0.0 #1.22.5版本Flutter用这个
  cached_network_image: ^3.2.0
  #图片显示
  photo_view: ^0.13.0
  flutter_sound: ^9.1.3
  #权限处理
  #  audioplayers: 0.13.3 #1.22.5版本Flutter用这个
  audioplayers: ^0.20.1
  #视频播放
  #  video_player: 0.10.11+2 #1.22.5版本Flutter用这个
  video_player: ^2.2.19
  #图片压缩
  flutter_image_compress: ^1.1.0
  #特殊列表滑动
  wechat_assets_picker: ^7.0.1
  flutter_picker: ^2.0.3
  emoji_picker_flutter: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/home/
    - assets/images/my/
    - assets/images/patient/
    - assets/images/svg/
    - assets/messages.json
  # To add assets to your application, add an assets section, like this:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Regular
      fonts:
        - asset: assets/fonts/PingFang-SC-Regular.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/PingFang-SC-Medium.ttf
    - family: ShouShuti
      fonts:
        - asset: assets/fonts/ShouShuti_Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
